version: '2.1'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.1
    container_name: zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:3.3.1
    container_name: kafka
    hostname: kafka
    restart: on-failure
    ports:
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSET_REPLICATION_FACTOR: 1
      ZOOKEEPER_SASL_ENABLED: 'false'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://KAFKA:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper